name: Deploy on fly.io

on:
  push:
    branches: [ trunk ]

jobs:
  deploy_app:
    runs-on: ubuntu-latest

    permissions:
      deployments: write
      contents: read

    # Only run one deployment at a time per commit.
    concurrency:
      group: tryzjit

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
