name: Deploy preview on fly.io

on:
  pull_request:
    branches: [ trunk ]
    types: [ opened, reopened, closed ]

jobs:
  stage_app:
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    # Only run one deployment at a time per PR.
    concurrency:
      group: tryzjit-pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: tryzjit-pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          name: tryzjit-pr-${{ github.event.number }}
          region: ewr
          org: personal
        env:
          DOCKER_BUILDKIT: 1
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
