name: Update Ruby

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update_ruby:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update Ruby revision in Dockerfile
        run: ./new-details.sh

      - name: Commit and push if changed
        run: |
          git diff --quiet && exit 0
          git config user.name "github-actions[bot]"
          git config user.email "github@bernsteinbear.com"
          git add Dockerfile
          git commit -m "Update Ruby"
          git push
